### ISSUE TITLE
[Bug] Musician makes raid frame show after targeting something/someone

### ISSUE THREAD

**Issue by Snahkstrasza** [LenweSaralonde/Musician#102]
### Description

When targeting someone or something Musician makes raid frames show

### Reproduction steps

1.Target someone/something
2.Raid Frames Show

### Actual behavior

Clicking on someone or something causes raid frames to show.

### Expected behavior

Raid frames not show when clicking someone/something

### Screenshots

![2024-08-1519-00-29-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/3521df60-29ef-4dcd-a6b3-60a8865c15f4)

### World of Warcraft flavor

Retail

### World of Warcraft version

11.0.2.56110

### Add-on version

1.9.10.1

### Have you tried disabling all your other add-ons to ensure only this add-on causes the issue?

Yes

**Comment by LenweSaralonde** [comment]
Resolved in 8c7fa3af9aac64134718e12fce58b24e743302fe
