### ISSUE TITLE
Emote

### ISSUE THREAD

**Issue by sfjuocekr** [LenweSaralonde/Musician#50]
I have this weird thing and I can't find the option or what I did different.

On my main I do not see the /me plays a song emote, I do on all my alts however!

What am I missing?

**Comment by LenweSaralonde** [comment]
Check in the options if the emote is enabled. Also check if you have the emotes visible in the chat window.

**Comment by sfjuocekr** [comment]
I checked, they are enabled and showing.

When I type /me bla it shows the emote as well.

**Comment by LenweSaralonde** [comment]
I can't help, emote settings are not bound to a character, it should be something else.

**Comment by sfjuocekr** [comment]
Ah, I figured it out.

Something Prat interferes with!
