### ISSUE TITLE
Musician Interface Options

### ISSUE THREAD

**Issue by Drizzard2** [LenweSaralonde/Musician#79]
Hey there,

I like to keep my interface clean. Is it possible for you to add an option to Musician that hides the Musician version of you and others around you on the tooltip? It adds an extra line to the bottom that needlessly extends the tooltip.

Further, is it possible to also add an option to hide the Musician minimap icon? I would love to be able to just leave musician on without it taking up any interface space.

The idea is to have musician running 'invisibly', no minimap icon, no tooltip, but still music of those around you.

**Comment by LenweSaralonde** [comment]
> Is it possible for you to add an option to Musician that hides the Musician version of you and others around you on the tooltip? It adds an extra line to the bottom that needlessly extends the tooltip.

Yes it's technically feasible but I will probably leave this unchanged, except if more users have concerns with this extra information in the player tooltip.

> Further, is it possible to also add an option to hide the Musician minimap icon? I would love to be able to just leave musician on without it taking up any interface space.

I suggest you to use the [HidingBar](https://www.curseforge.com/wow/addons/hidingbar) add-on that allows you to move the add-on minimap icons to a tray so you can have a clean minimap with no extra button overlapping.
