### ISSUE TITLE
[Bug] SFX Level

### ISSUE THREAD

**Issue by SugeNova** [LenweSaralonde/Musician#91]
### Description

It may be just me, but every time I lower the effects volume while Musician is active, At the moment I close the options tab, the effects returns to be 100%,

### Reproduction steps

1.Lower the effects volume
2. Close the options tab
3. When you press esc again, the volume didn't lowered

### Actual behavior

Musician addon doesn't let me lower the volume at all

### Expected behavior

Should let me lower the volume slider without returning to its original position once I closed the options tab

### World of Warcraft flavor

Retail

### World of Warcraft version

10.0.2

### Add-on version

1.9.6.3

### Have you tried disabling all your other add-ons to ensure only this add-on causes the issue?

Yes

**Comment by LenweSaralonde** [comment]
This is not a bug. Musician sets SFX and Dialog volume to the maximum by default to increase the amount of simultaneous notes. You can disable this in the settings, for example to use only the Master channel and don't have the volume adjusted.

https://github.com/LenweSaralonde/Musician/wiki/What-the-FAQ#why-are-my-sound-and-dialog-volume-settings-constantly-being-adjusted-to-the-maximum
