### ISSUE TITLE
[Bug] Elvui party frames don't load (probably raid ones too)

### ISSUE THREAD

**Issue by DarkLCF** [LenweSaralonde/Musician#96]
### Description

when using this addon the elvui party frames will just not appear, at all (most of the time), until you reload. with 0 errors.

### Reproduction steps

1.have elvui
2.have this addon
3.get in a party

### Actual behavior

it's clear enough

### Expected behavior

it shouldn't fuck anything

### World of Warcraft flavor

Retail

### World of Warcraft version

10.1.7.51754

### Add-on version

1.9.8.8

### Have you tried disabling all your other add-ons to ensure only this add-on causes the issue?

Yes

### Additional context

this isn't new it's been happening for months

**Comment by LenweSaralonde** [comment]
@DarkLCF I was unable to reproduce the problem. I used a fresh installation of ElvUI with the default settings and the party frames always show up properly.

Please do the following : 
* Have the latest version of Musician and ElvUI.
* Make sure errors are visible. Type `/console scriptErrors 1` to enable them. In addition, some addons such as BugSack may hide errors, you have to open BugSack to see the errors.
* Try disabling Musician and check that the problem doesn't occur anymore with a 100% success rate.
* Be more precise in the steps to reproduce the problem (was it after right after the loading screen ? Were you in a party before ? etc.).

Could you please attach the 2 `ElvUI.lua` files that are located in the following folders ?
```
World of Warcraft\_retail_\WTF\Account\<account name>\SavedVariables\ElvUI.lua
World of Warcraft\_retail_\WTF\Account\<account name>\<realm name>\<character name>\SavedVariables\ElvUI.lua
```

**Comment by DarkLCF** [comment]
i tried using only musician and elvui and entering the horseman queue and it didn't happen, getting invited by a friend it didn't happen with all other addons even. it has happened a lot of times when getting invited through the dungeons and raids system both when queued for random (so yes loading screen) but also just through premade (no loading screen) but well i had all my addons not just those 2.

even with errors enabled nothing shows like i said /shrug
when it happens the party frames will just simply not be there. until reloading like i mentioned. and yeah it hasn't happened with both stock and shadowed unit frames, only elvui ones

without musician this has never happened which is why i got rid of this addon (and why i posted this)
[elvuiwtf.zip](https://github.com/LenweSaralonde/Musician/files/13124763/elvuiwtf.zip)
i will try to investigate it more

edit1: the profile used is "Default" for both general and private
edit2: i will close this issue for now because i also had trouble replicating it the last few days.

**Comment by DarkLCF** [comment]
and then it decided to happen again today anyway, while inviting a bnet friend cross faction, but then it also didn't. yeah i have no idea how to replicate it consistently but it does happen, and it has never happened without this addon in months, and it has happened with this addon for months at (usually frequent) times ¯\_(ツ)_/¯

**Comment by LenweSaralonde** [comment]
There is another bug with ElvUI that may occur on rare occasions #97

I wasn't able to reproduce it either but the fix is straightforward, hopefully it will resolve this one too.

**Comment by DarkLCF** [comment]
alright i installed the new update, and the issue is still there (still investigating how to reproduce it more consistently, and i think i have a clue just needs a lot more testing to be sure).
i also noticed more things about it, so the first thing is that the frames are not actually gone at all, they do exist in their place, they are clickable, they are mouseoverable, but they are completely invisible. and a ui reload is not required, going to the elvui menu and toggling the display button brings them back.
i will try to include a video or a gif showcasing the problem either here or on the discord tomorrow.

**Comment by LenweSaralonde** [comment]
Issue seems to appear on cold start after quick preloading

https://github.com/LenweSaralonde/Musician/assets/34239920/efbad8f3-0c14-40b6-803e-ce5662530a1b
