### ISSUE TITLE
[Bug] Lua error when playing in instances

### ISSUE THREAD

**Issue by keyboardturner** [LenweSaralonde/Musician#98]
### Description

207x bad argument #1 to '?' (outside of expected range -2147483648 to 2147483647 - Usage: local uiMapID, mapPosition = C_Map.GetMapPosFromWorldPos(continentID, worldPosition [, overrideUiMapID]))
[string "=[C]"]: in function `GetMapPosFromWorldPos'
[string "@Musician/modules/MusicianMap/MusicianMap.lua"]:40: in function <Musician/modules/MusicianMap/MusicianMap.lua:38>
[string "@Musician/modules/MusicianMap/MusicianMap.lua"]:117: in function <Musician/modules/MusicianMap/MusicianMap.lua:93>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Musician/core/Musician.Comm.lua"]:472: in function `ProcessChunk'
[string "@Musician/core/Musician.Comm.lua"]:581: in function <Musician/core/Musician.Comm.lua:556>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceComm-3.0-12/AceComm-3.0.lua"]:260: in function <...ceDataStore/libs/AceComm-3.0/AceComm-3.0.lua:242>

Locals:
(*temporary) = "bad argument #1 to '?' (outside of expected range -2147483648 to 2147483647 - Usage: local uiMapID, mapPosition = C_Map.GetMapPosFromWorldPos(continentID, worldPosition [, overrideUiMapID]))"

### Reproduction steps

1. Sit in Valdrakken, probably when somebody is trying to play music somewhere

### Actual behavior

error

### Expected behavior

no error

### Screenshots

![image](https://github.com/LenweSaralonde/Musician/assets/20036792/b4e8c478-e3c3-485e-9454-370faf88741e)

### World of Warcraft flavor

Retail

### World of Warcraft version

10.2.5.52902

### Add-on version

1.9.8.9

### Have you tried disabling all your other add-ons to ensure only this add-on causes the issue?

No

### Additional context

bingus

**Comment by LenweSaralonde** [comment]
This occurs when someone is playing music in an instance.
